version: '3'
services:
  mysql-siu:
    image: 'mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=sportitup
    ports:
      - 3308:3306
  
  
  springboot-docker-container:
    image: nihar01/sportitup
    ports:
      - 8081:8081
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-siu:3306/sportitup
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    depends_on:
      - mysql-siu
  
  react-docker-container:
    image: nihar01/sportitup-frontend
    ports:
      - 80:80
    depends_on:
      - springboot-docker-container
